"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import "./auth.css";
const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
export default function AuthPage() {
  const [mode,setMode]=useState<"login"|"register">("login"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false); const register=mode==="register";
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");try{const r=await fetch(`${API}/api/v1/auth/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(register?{name,email,password}:{email,password})});const b=await r.json();if(!r.ok)throw Error(typeof b.detail==="string"?b.detail:"Không thể xác thực.");localStorage.setItem("cario-auth",JSON.stringify(b));location.assign("/workspace")}catch(x){setError(x instanceof Error?x.message:"Không thể xác thực.")}finally{setLoading(false)}}
  return <main className="auth-page"><header><Link className="auth-brand" href="/">✳ CARIO<span>.</span></Link><Link href="/">Về trang giới thiệu</Link></header><div className="auth-grid"><section className="auth-story"><p>CARIO không chọn nghề thay bạn.</p><h1>Hiểu mình.<br/>Thử một việc.<br/>Đi tiếp có cơ sở.</h1><ol><li><b>01</b>Khám phá điều bạn quan tâm</li><li><b>02</b>Thử một Career Quest</li><li><b>03</b>Lưu bằng chứng năng lực</li></ol></section><section className="auth-card"><p>{register?"Tạo tài khoản":"Đăng nhập"}</p><h2>{register?"Bắt đầu hành trình của bạn":"Tiếp tục hành trình của bạn"}</h2><form onSubmit={submit}>{register&&<label>Họ tên<input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu<input type="password" required minLength={8} autoComplete={register?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={loading}>{loading?"Đang xử lý…":register?"Tạo tài khoản":"Đăng nhập"}</button></form>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="auth-switch" type="button" onClick={()=>{setMode(register?"login":"register");setError("")}}>{register?"Đã có tài khoản? Đăng nhập":"Chưa có tài khoản? Tạo tài khoản"}</button></section></div></main>
}
